apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: configuration
  namespace: default
spec:
  type: configuration.redis
  version: v1
  metadata:
  - name: redisHost
    value: host.docker.internal:6379
  - name: redisPassword
    value: ""