# Avalanche CMS Local Stack

version: '3.8'
name: avalanchecms

# Network setup
networks:
  avalanchecms:
    driver: bridge  # Bridge driver for container communication

# Services
services:

  # PostgreSQL Database
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    networks:
      - avalanchecms
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD_FILE: /run/secrets/avalanchecms/postgres-admin-user-secret.env
      AV_APP_NAME: PostgreSQL
      AV_ORIGINAL_ENTRYPOINT: docker-entrypoint.sh
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/avalanchecms-init-db.sh:ro
      - ./scripts:/usr/local/bin/avalanchecms:ro
      - ./config:/etc/avalanchecms:ro
      - ./../../.secrets:/run/secrets/avalanchecms:ro
    entrypoint: /usr/local/bin/avalanchecms/entrypoint.sh
    command: ["postgres"]

  # pgAdmin Database Management
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8
    restart: always
    depends_on:
      - postgres
    ports:
      - "5050:80" # UI: http://localhost:5050/
    networks:
      - avalanchecms
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@avalanchecms.com # admin user
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/avalanchecms/pgadmin-admin-user-secret.env
      PGADMIN_SERVER_JSON_FILE: /etc/avalanchecms/pgadmin-config.json
      AV_APP_NAME: pgAdmin
      AV_ORIGINAL_ENTRYPOINT: /entrypoint.sh
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./scripts:/usr/local/bin/avalanchecms:ro
      - ./config:/etc/avalanchecms:ro
      - ./../../.secrets:/run/secrets/avalanchecms:ro
    entrypoint: /usr/local/bin/avalanchecms/entrypoint.sh

  # Keycloak IAM
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080" # UI: http://localhost:8080/
    networks:
      - avalanchecms
    environment:
      KEYCLOAK_ADMIN: admin # admin user
      KEYCLOAK_ADMIN_PASSWORD_FILE: /run/secrets/avalanchecms/keycloak-admin-user-secret.env
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD_FILE: /run/secrets/avalanchecms/postgres-keycloak-db-user-secret.env
      KC_DB_URL_SSL_ENABLED: false
      AV_APP_NAME: Keycloak
      AV_ORIGINAL_ENTRYPOINT: /opt/keycloak/bin/kc.sh
      AV_LOAD_SECRET_ENVS: true
      AV_CUSTOM_SCRIPT: /usr/local/bin/avalanchecms/set-keycloak-env.sh
    volumes:
      - ./config/keycloak-realm-config.json:/opt/keycloak/data/import/keycloak-realm-config.json:ro
      - ./scripts:/usr/local/bin/avalanchecms:ro
      - ./config:/etc/avalanchecms:ro
      - ./../../.secrets:/run/secrets/avalanchecms:ro
    entrypoint: /usr/local/bin/avalanchecms/entrypoint.sh
    command: ["start-dev", "--import-realm"] # Development mode, never use for production
  
# Storage Volumes
volumes:
  pgadmin-data:
  postgres-data:
